Repository wecode-bootcamp-korea/13-DEV101-frontend, pull requests merged in 2020-11, with the labels that each got.

#4 [DEV101 구현정] Refactor: 개발환경 재수정! (20.11.04)
  .eslintrc
  .eslintrc.json
  package-lock.json
  package.json
  public/index.html
  src/Routes.js
  src/Styles/common.js
  src/Styles/common.scss
  src/Styles/reset.scss
  src/store/store.js
Labels: Status: Accepted

#1 [13기 구현정] Refactor : 카드 컴포넌트 리팩토링 및 필요데이터 로직 구현
  .gitattributes
  package-lock.json
  package.json
  src/Components/ClassCard.js
  src/Components/component.js
  src/Pages/pages.js
  src/Routes.js
  src/Styles/reset.scss
  src/index.js
Labels: Status: Accepted

#2 [DEV101 전민승] Refactor: resolved loginPage codeReview
  .eslintrc.json
  config.js
  debug.log
  package-lock.json
  package.json
  public/Images/dev101.png
  public/Images/images
  public/index.html
  src/Components/Nav/Nav.js
  src/Components/component.js
  src/Pages/Login/Login.js
  src/Pages/Login/LoginAnother.js
  src/Pages/SignUp/SignUp.js
  src/Pages/pages.js
  src/Routes.js
  src/config.js
Labels: Status: Conflict 해결 요청, Status: 수정 요청

#3 [DEV101 김보라] Refactor: 마이페이지 리팩토링 및 conflict 해결
  package-lock.json
  package.json
  public/Data/myPageList.json
  public/Data/myPageMockData.json
  public/Images/pointIcon.png
  src/Pages/MyPage/MyPage.js
  src/Pages/MyPage/MyPageComponent/LeftMenuCard.js
  src/Pages/MyPage/MyPageComponent/MyPageSlider.js
  src/Routes.js
Labels: Status: 리뷰 요청

#8 [DEV101 구현정] Fix: Conflict 해결 및 InfiniteScroll 수정
  package.json
  public/Data/data.json
  src/Components/ClassCard.js
  src/Components/InfiniteScroll.js
  src/Components/Nav/Nav.js
  src/Components/SliderComponent.js
  src/Pages/Main/Data.js
  src/Pages/Main/Main.js
  src/Pages/Main/components/MainSlider.js
  src/Pages/Main/components/SubBanner.js
  src/Pages/Main/images/banner2.jpg
  src/Pages/Main/images/left.png
  src/Pages/Main/images/right.png
  src/Pages/Main/images/subBanner01.jpg
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#11 [DEV101 함준호] FIX: rebase 문제 해결
  .gitattributes 
  .prettierrc
  public/Data/Detail.json
  public/Data/data.json
  public/Images/images
  src/Components/ClassCard.js
  src/Components/Nav/Nav.js
  src/Pages/Detail/Aside.js
  src/Pages/Detail/Components/Banner.js
  src/Pages/Detail/Components/Button.js
  src/Pages/Detail/Components/Community.js
  src/Pages/Detail/Components/CommunityComment.js
  src/Pages/Detail/Components/CommunityPost.js
  src/Pages/Detail/Components/CreatorMessage.js
  src/Pages/Detail/Components/HeadModal.js
  src/Pages/Detail/Components/LearningGoal.js
  src/Pages/Detail/Components/Review.js
  src/Pages/Detail/Components/ReviewComment.js
  src/Pages/Detail/Components/Utils.js
  src/Pages/Detail/Components/WhatIsClass.js
  src/Pages/Detail/TopHeader.js
  src/Pages/Detail/index.js
  src/Pages/Login/Login.js
  src/Pages/Login/LoginAnother.js
  src/Pages/Payment/index.js
  src/Pages/SignUp/SignUp.js
  src/Routes.js
  src/Styles/common.js
  src/Styles/reset.scss
  src/index.js
  src/store/CreatorsReducer.js
  src/store/DetailReducer.js
  src/store/store.js
Labels: Status: 리뷰 진행중

#16 [DEV101 함준호] prettierrc 파일 수정
  .eslintrc.json
  .prettierrc
  src/Components/ClassCard.js
  src/Components/Nav/Nav.js
  src/Pages/Creators/Chapter/Intro.js
  src/Pages/Detail/Aside.js
  src/Pages/Detail/Components/Button.js
  src/Pages/Detail/Components/CommunityPost.js
  src/Pages/Detail/Components/CreatorMessage.js
  src/Pages/Detail/Components/HeadModal.js
  src/Pages/Detail/Components/LearningGoal.js
  src/Pages/Detail/Components/Review.js
  src/Pages/Detail/Components/ReviewComment.js
  src/Pages/Detail/Components/Utils.js
  src/Pages/Detail/TopHeader.js
  src/Pages/Detail/index.js
  src/Pages/Login/Login.js
  src/Pages/Login/LoginAnother.js
  src/Pages/MyPage/MyPageComponent/MyPageSlider.js
  src/Pages/Payment/index.js
  src/Pages/SignUp/SignUp.js
  src/Pages/pages.js
  src/Routes.js
Labels: Status: 도움 요청

#7 [DEV101 전민승] Refactor: signUp 코드리뷰사항 반영
  .gitignore
  debug.log
  package-lock.json
  src/Pages/Login/Login.js
  src/Pages/Login/LoginAnother.js
  src/Pages/SignUp/SignUp.js
  src/Routes.js
Labels: Status: 리뷰 요청

#10 [DEV 101 전민승] Refactor: Nav 코드리뷰사항 반영
  src/Components/Nav/Nav.js
  src/Pages/Login/Login.js
  src/Routes.js
Labels: Status: 리뷰 요청

#17 [DEV101 함준호] heart 토글시 값이 이상하게 변하던 것 수정
  src/Pages/Detail/Aside.js
  src/Pages/Detail/Components/CommunityPost.js
  src/Pages/Detail/Components/Review.js
  src/Pages/Detail/Components/Utils.js
  src/Pages/Detail/index.js
Labels: Status: 수정 요청

#13 [DEV101 김보라] Refactor: 검색 결과 페이지 리팩토링
  package-lock.json
  package.json
  public/Data/searchCardData.json
  public/Images/banner1.jpg
  public/Images/banner2.jpg
  public/index.html
  src/Pages/SearchPage/SearchPage.js
  src/Pages/SearchPage/SearchPageComponent/FilterBtnModal.js
  src/Pages/SearchPage/SearchPageComponent/MordalPortal.js
  src/Pages/SearchPage/SearchPageComponent/SearchBanner.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#15 [DEV101 김보라] Fix: 마이페이지 conflict 해결 및 수정
  public/Data/myPageMockData.json
  src/Pages/Login/LoginAnother.js
  src/Pages/MyPage/MyPage.js
  src/Pages/MyPage/MyPageComponent/ClassMadeCard.js
  src/Pages/MyPage/MyPageComponent/MyClassCard.js
  src/Pages/MyPage/MyPageComponent/MyPageSlider.js
  src/config.js
Labels: Status: 리뷰 진행중

#18 [DEV 101 구현정] Add: Footer 컴포넌트
  src/Components/Footer.js
  src/Components/FooterInfo.js
  src/Routes.js
Labels: Status: 리뷰 요청

#19 [DEV101 함준호] 크리에이터 생성 페이지 레이아웃 & 기능구현
  package-lock.json
  package.json
  public/Images/images
  src/Components/Nav/Nav.js
  src/Pages/Creators/Chapter/Last.js
  src/Pages/Creators/Components/Aside.js
  src/Pages/Creators/Components/Footer.js
  src/Pages/Creators/Components/Nav.js
  src/Pages/Creators/Components/Slick.js
  src/Pages/utils.js
  src/Routes.js
  src/store/CreatorsReducer.js
  src/store/store.js
Labels: Status: 리뷰 요청

#20 [DEV101 김보라] Modify: 검색 결과 페이지 수정
  src/Components/Nav/Nav.js
  src/Pages/SearchPage/SearchPage.js
  src/Routes.js
Labels: Status: 리뷰 요청

#23 [DEV101 구현정] Add: 카테고리 페이지 재제작
  src/Pages/Category/Category.js
  src/Pages/Category/Data.js
  src/Pages/Category/SubBanner.js
  src/Pages/Category/components/CategoryBanner.js
  src/Pages/Category/components/MainBanner.js
  src/Pages/Category/components/SubBanner.js
  src/Pages/Category/images/banner2.jpg
  src/Pages/Category/images/career.jpg
  src/Pages/Category/images/creative.jpg
  src/Pages/Category/images/left.png
  src/Pages/Category/images/right.png
  src/Pages/Category/images/subBanner01.jpg
  src/Routes.js
Labels: Status: 리뷰 요청

#24 [DEV101 함준호] FIX: 특정 페이지에서 nav ,footer 안보이게 수정
  src/Components/Footer.js
  src/Components/Nav/Nav.js
Labels: Status: 도움 요청

#22 [DEV101 구현정] Fix: 최종 수정!!!!
  src/Components/ClassCard.js
  src/Components/InfiniteScroll.js
  src/Components/IsPlannedModal.js
  src/Components/IsPlannedModalContents.js
  src/Components/Nav/Nav.js
  src/Components/ScrollToTop.js
  src/Components/SliderComponent.js
  src/Pages/Category/Category.js
  src/Pages/Category/components/CategoryBanner.js
  src/Pages/Category/components/MainBanner.js
  src/Pages/Creators/Components/Footer.js
  src/Pages/Creators/index.js
  src/Pages/Detail/Aside.js
  src/Pages/Detail/Components/CommunityPost.js
  src/Pages/Detail/TopHeader.js
  src/Pages/Detail/index.js
  src/Pages/Login/Login.js
  src/Pages/Login/LoginAnother.js
  src/Pages/Main/Main.js
  src/Pages/Main/components/MainSlider.js
  src/Pages/MyPage/MyPage.js
  src/Pages/MyPage/MyPageComponent/ClassMadeCard.js
  src/Pages/PackageSelector/index.js
  src/Pages/Payment/index.js
  src/Pages/SignUp/SignUp.js
  src/Routes.js
Labels: Status: 리뷰 요청
